name: gotify
services:
  gotify:
    image: gotify/server-arm64:2.4.0
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - target: 80
        published: "2222"
        protocol: tcp
    restart: always
    environment:
      TZ: $TZ
      GOTIFY_DATABASE_DIALECT: sqlite3
      GOTIFY_DATABASE_CONNECTION: /gotify/data/gotify.db
      GOTIFY_DEFAULTUSER_NAME: casaos
      GOTIFY_DEFAULTUSER_PASS: casaos
      GOTIFY_PASSSTRENGTH: 10
      GOTIFY_UPLOADEDIMAGESDIR: /gotify/data/images
      GOTIFY_PLUGINSDIR: /gotify/data/plugins
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/data
        target: /gotify/data
    x-casaos:
      ports:
        - container: "80"
          description:
            en_us: ""
      volumes:
        - container: /gotify/data
          description:
            en_us: "data from gotify"
            fr_fr: "Donnée de gotify"
    container_name: gotify
x-casaos:
  architectures:
    - arm64
  main: Gotify
  author: ProBreizh35
  developer: Gotify
  category: Utilities
  description:
    en_us: Gotify is a self-hosted notification system
    fr_fr: Gotify est un system de notification auto heberger
  tips:
    before_install:
      fr_fr:  |
        Pseudo: casaos
        Mots de passe : casaos
        Petit + pour les notification via qbtorrent ; allez dans les paramètre, téléchargement et dans éxecuter un programe externe entré curl "https://push.example.de/message?token=<apptoken>" -F "title=my title" -F "message=my message" -F "priority=5".
        Biensur remplacer "https://push.example.de" et "<apptoken>" par vos informations !