name: gotify
services:
  gotify:
    image: gotify/server-arm64:2.4.0
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - target: 80
        published: "2222"
        protocol: tcp
    restart: always
    environment:
      TZ: $TZ
      GOTIFY_DATABASE_DIALECT: sqlite3
      GOTIFY_DATABASE_CONNECTION: data/gotify.db
      GOTIFY_DEFAULTUSER_NAME: admin
      GOTIFY_DEFAULTUSER_PASS: Bzh354422.@#{
      GOTIFY_PASSSTRENGTH: 10
      GOTIFY_UPLOADEDIMAGESDIR: data/images
      GOTIFY_PLUGINSDIR: data/plugins
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/data
        target: /gotify
    x-casaos:
      ports:
        - container: "80"
          description:
            en_us: ""
      volumes:
        - container: /gotify
          description:
            en_us: ""
    container_name: gotify
x-casaos:
  architectures:
    - amd64
    - "386"
    - arm64
    - arm
  main: Gotify
  author: ProBreizh35
  category: Utilities
  description:
    fr_fr: Gotify est un system de notification auto heberger